### ISSUE TITLE
Problem with Clojure 1.8 direct linking?

### ISSUE THREAD

**Issue by emlyn** [gar3thjon3s/lein-expectations#10]
If I compile my app with Clojure 1.8 with direct linking enabled (by adding `"-Dclojure.compiler.direct-linking=true"` to the `:jvm-opts`), expectations doesn't run, but just prints `Unable to read results.` and quits.
I was unable to reproduce this in a new empty project, so it may be an interaction with some other setting or dependency.

**Comment by seancorfield** [comment]
Yes, Expectations relies on dynamic rebinding for some of its features so you cannot use direct linking when testing. Note that direct linking also interferes with the normal REPL-driven development workflow in Clojure since re-`defn`-ing a function will not cause references to it to pick up the new version.
